name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:
    name: Compile Ubuntu Binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make M68K
      run: make CPU=m68k SYNTAX=psi-x
    - name: Make Z80
      run: make CPU=z80 SYNTAX=psi-x
    - name: Make 6502
      run: make CPU=6502 SYNTAX=psi-x
      run: |
        mkdir artifacts
        mv vasmm68k_psi-x artifacts
        mv vasmz80_psi-x artifacts
        mv vasm6502_psi-x artifacts

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.6        
        with: 
          name: ubuntu-builds
          path: artifacts
          retention-days: 30

  build-windows:
    name: Compile Windows Binaries
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make M68K
      run: make CPU=m68k SYNTAX=psi-x
    - name: Make Z80
      run: make CPU=z80 SYNTAX=psi-x
    - name: Make 6502
      run: make CPU=6502 SYNTAX=psi-x

  build-macos:
    name: Compile MacOS Binaries
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make M68K
      run: make CPU=m68k SYNTAX=psi-x
    - name: Make Z80
      run: make CPU=z80 SYNTAX=psi-x
    - name: Make 6502
      run: make CPU=6502 SYNTAX=psi-x
